version: '3.8'
services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000  # Define backend URL for React app

  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "4000:4000"  # Expose backend on port 4000
    environment:
      - DB_URI=mongodb+srv://aftabsayyad9502:GGBbibDl3bfPgX4B@cluster0.5f9if.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0  # MongoDB Atlas URI
      - PORT=4000  # Port for backend server
    networks:
      - app-network

volumes:
  mongodb_data:  # (Not necessary since you're using MongoDB Atlas)

networks:
  app-network:  # This network allows containers to communicate with each other
    driver: bridge
